use std::{fs::File, path::Path};

use wikimedia_language_codegen::{languages_as_enum_code, languages_from_sitematrix, site_matrix};

fn main() {
    let site_matrix = site_matrix();

    let languages = languages_from_sitematrix(&site_matrix);

    let code = languages_as_enum_code(languages);

    let code_string = format!(
        "// Generated by wikimedia-language-codegen\n\n{}",
        code.to_string()
    );

    let mut file = File::create(Path::new(
        "crates/wikimedia-language-codegen/output/wikimedia_languages.rs",
    ))
    .expect("Failed to create output file");

    std::io::Write::write_all(&mut file, code_string.as_bytes())
        .expect("Failed to write code to file");
}
